- name: OS - Ensure temporary directory exists
  ansible.builtin.file:
    path: /tmp
    state: directory
    owner: root
    group: root

- name: OS - Copy Splunk SOAR installation package
  ansible.builtin.copy:
    src: files/{{ splunk_soar_package }}
    dest: /tmp/{{ splunk_soar_package }}
    mode: preserve