---
- name: OS - Copy Splunk SOAR installation package
  ansible.builtin.copy:
    src: files/{{ splunk_soar_package }}
    dest: "{{splunk_soar_download_location}}/{{ splunk_soar_package }}"
    owner: "{{ splunk_soar_user }}"
    group: "{{ splunk_soar_group }}"
    mode: "0644"