---
- name: OS - Set ownership of Splunk SOAR installation directory
  ansible.builtin.file:
    path: /opt/phantom
    owner: "{{ splunk_soar_user }}"
    group: "{{ splunk_soar_group }}"
    recurse: true

- name: OS - Set ownership of Splunk SOAR installation files
  ansible.builtin.file:
    path: /opt/splunk-soar
    owner: "{{ splunk_soar_user }}"
    group: "{{ splunk_soar_group }}"
    recurse: true
    
- name: Splunk SOAR - Run installation script
  ansible.builtin.shell:
    cmd: |
      yes y | ./soar-install --splunk-soar-home "{{ splunk_soar_home }}"
    chdir: "/opt/splunk-soar/"
    creates: "/opt/phantom/bin"
  become_user: "{{ splunk_soar_user }}"
  when: soar_prepare_result.rc == 0
