---
- name: Firewall - Install firewalld package
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Firewall - Ensure firewalld service is enabled and running
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: true